### ISSUE TITLE
Minimum Windows Version to Run Appx & Certificate Questions.

### ISSUE THREAD

**Issue by KevinMartin** [CatalystCode/electron-windows-store#16]
I have 2 questions:

1. I understand that to build the Appx, I need Windows 10 AU. But will my users also need at least this version in order to run the application?
  * The reason I ask is the [Electron documentation](https://github.com/electron/electron/blob/master/docs/tutorial/windows-store-guide.md) seems a bit ambiguous with the text:
  * "With Windows 8, the good old win32 exectuable got a new sibling: The Universial Windows Platform."
  * Does this mean Windows 8+ can also run the application?
2. When Window AU is released, will I have to use a "Microsoft Certificate" or can I use an Authenticode Certficate that I already have purchased? or are those the same thing?

Edit: 3. Where can I get a Microsoft Certificate?

**Comment by felixrieseberg** [comment]
1) Yep, they will need Windows 10. The good news is that the AU isn't anything crazy big, people will just get it as a normal update.

2) You only need the Microsoft certificate if you want to distribute your app via the Windows Store. You'll get said certificate while signing up for the [Windows Developer Program](https://developer.microsoft.com/en-us/windows), which doesn't have a yearly fee, but a $19 signup fee. You can't submit Electron AppX packages just yet, but we're working hard on it ;-)

**Comment by FullR** [comment]
> Yep, they will need Windows 10

Does this mean the packaged app will not be available to Windows 8 users even once it has been published to the Windows Store? Or is Windows 10 only required to run the appx as a standalone file?

**Comment by SebastiaandenBoer** [comment]
These packaged apps will require the Windows 10 AU to run, which of course won't be the case when running any version of Windows 8. Your packages created using this tool will not work on any version lower than the Windows 10 AU, which is supposedly now installed on +- 75% of Win 10 machines.

It is however possible, to create multiple packages with different tools for the same app. Therefore, you could a package created with this tool published, targeting Windows 10 AU, alongside another package (C# or JS), targeting all versions of Windows 8 and the versions of Windows 10 pre-AU.

**Comment by felixrieseberg** [comment]
@SebastiaandenBoer ☝️ Exactemundo!
