### ISSUE TITLE
issues with the generated xml file

### ISSUE THREAD

**Issue by belaviyo** [CatalystCode/electron-windows-store#17]
Although the generated appx file works as expected I got the following errors during app submission
```
Package acceptance validation error: We don’t allow the capability you’ve specified: runFullTrust.
Package acceptance validation error: The PublisherDisplayName element in the app manifest of TDM.appx is Reserved, which doesn't match your publisher display name: *****.
Package acceptance validation error: You don't have permissions to specify the following namespaces in the appx manifest file of the package TDM.appx: http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities
```

If I remove the `runFullTrust` capability as well as the namespace, electron app would not run anymore (even the hello world example). I am not sure how to debug this appx.

**Comment by felixrieseberg** [comment]
Hey! Sorry to say that submission is still in the works and will be possible with Windows 10 Anniversary Update, which will be ready for people this summer.

https://www.microsoft.com/en-us/windows/upcoming-features

(Closing this in the meantime - the XML is fine, we're just waiting for the store ;-))

**Comment by belaviyo** [comment]
@felixrieseberg so do we really need the [`runFullTrust` capability](https://github.com/CatalystCode/electron-windows-store/blob/master/template/appxmanifest.xml#L22)? `internetClient` capability seems to be just fine for a simple app.

```
<Capabilities>
  <Capability Name="internetClient"/>
</Capabilities>
```

One other question. Do you happen to kow how I can debug the generated appx. I can install it but not sure how to debug it.

**Comment by benoror** [comment]
Hi @felixrieseberg ! We just stumbled upon this very same issue while submitting our app to the Windows Store, is there any **update** regarding the status? 

Windows 10 Anniversary Update is [supposely coming soon](https://blogs.windows.com/windowsexperience/2016/06/29/windows-10-anniversary-update-available-august-2/), Is there a **workaround** for submitting the app in the meantime? 

Thanks :smile:!

**Comment by felixrieseberg** [comment]
Hey! Sorry to say that `runFullTrust` is what makes the whole application work. We're working with a few selected companies right now to iron out the edges, but submission should be available "soon". We still don't have a date yet, but as soon as we do, I'll make sure to let people know!

**Comment by black-snow** [comment]
@felixrieseberg Hey there. Anniversary has been around for a while so I wanted to push my app to the store.
Sadly this is what happens:

* Complaint about `PublisherDisplayName` being `Reserved`
* Complaint about `http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities`

And also `Your developer account doesn’t have permission to submit apps converted with the Desktop Bridge at this time.` - but I guess I'll just have to fill out that form.

Please reopen the issue.
