### ISSUE TITLE
SyntaxError: Unexpected token =>

### ISSUE THREAD

**Issue by JohanTh** [CatalystCode/electron-windows-store#24]
I'm having problems making this work:

> C:\\>electron-windows-store --input-directory C:\\...\\app\\.electrify\\.dist\\my-electrified-app-win32-x64  --output-directory C:\aaaa\myelectronapp --flatten true --package-version 1.0.0.0 --package-name myelectronapp
> C:\Users\gatsu\AppData\Roaming\npm\node_modules\electron-windows-store\bin\windowsstore.js:28
> -flatten <true|false>', 'Flatten Node modules without warning', (i) => (i ===
>                                                                     ^^
> SyntaxError: Unexpected token =>
>     at exports.runInThisContext (vm.js:73:16)
>     at Module._compile (module.js:443:25)
>     at Object.Module._extensions..js (module.js:478:10)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Function.Module.runMain (module.js:501:10)
>     at startup (node.js:129:16)
>     at node.js:814:3

**Comment by felixrieseberg** [comment]
Hey, thanks for reporting! Quick question: Which version of Node are you running? We're asking for one of the later versions :wink:

**Comment by JohanTh** [comment]
yes, ops, I was using an old version, thank you!
