### ISSUE TITLE
Handle long path

### ISSUE THREAD

**Issue by ritazh** [CatalystCode/electron-windows-store#3]
Handle apps that have long file path. "Move-Item : The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters."

**Comment by felixrieseberg** [comment]
I have hopes that deduping the npm dependencies should be enough, so we should probably incorporate npm-flatten or one of those tools into our little tool here, automatically flattening packages before we zip.

**Comment by ritazh** [comment]
Closed via d995c0c
